apiVersion: v1
kind: ConfigMap
metadata:
  name: maria-config
data:
  kkycake.sql: |
    CREATE DATABASE IF NOT EXISTS mydb;
    USE mydb;

    CREATE TABLE IF NOT EXISTS users (
        id VARCHAR(20) PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        phone VARCHAR(12) NULL,
        password VARCHAR(255) NOT NULL,
        registration_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS survey (
        browser VARCHAR(1) NOT NULL,
        upper VARCHAR(1) NOT NULL,
        pants VARCHAR(1) NOT NULL,
        shoes VARCHAR(1) NOT NULL,
        service VARCHAR(1) NOT NULL,
        registration_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    INSERT INTO users (id, password, name,phone) VALUES ('kkycake', 'rlarkdud1019', 'kayoung','01053161344');
    INSERT INTO survey (browser,upper,pants,shoes,service) VALUES ('5','5','5','5','5');
